import type { ResourceDefinition, SchemaProperty } from '../schema/index.js';

/** Options controlling code generation output. */
export interface EmitOptions {
  /** Prefix all interface properties with `readonly`. Default: false. */
  readonly?: boolean;
}

/**
 * Generate TypeScript source code for a group of resource definitions.
 * Produces one file per API group containing interfaces and typed Resource subclasses.
 */
export function generateGroupFile(
  group: string,
  defs: ResourceDefinition[],
  options: EmitOptions = {},
): string {
  const lines: string[] = [];

  lines.push(`// Generated by @xplane/codegen — do not edit`);
  lines.push(`import { type Construct } from "constructs";`);
  lines.push(`import { Resource, type ResourceConfig } from "@xplane/core";`);
  lines.push('');

  // Track export mappings: fully-qualified name → short name
  const typeExports: { fqName: string; shortName: string }[] = [];
  const valueExports: { fqName: string; shortName: string }[] = [];

  for (const def of defs) {
    const prefix = groupVersionToNamespace(group, def.version);
    lines.push(...generateResourceTypes(def, options, prefix));
    lines.push('');

    const fqClass = prefix + def.kind;
    typeExports.push({ fqName: `${fqClass}Spec`, shortName: `${def.kind}Spec` });
    typeExports.push({ fqName: `${fqClass}SpecInput`, shortName: `${def.kind}SpecInput` });
    typeExports.push({ fqName: `${fqClass}Status`, shortName: `${def.kind}Status` });
    typeExports.push({ fqName: `${fqClass}Props`, shortName: `${def.kind}Props` });
    valueExports.push({ fqName: fqClass, shortName: def.kind });
  }

  // Export block remapping fully-qualified names to short names
  lines.push('export type {');
  for (const { fqName, shortName } of typeExports) {
    lines.push(`\t${fqName} as ${shortName},`);
  }
  lines.push('};');
  lines.push('');
  lines.push('export {');
  for (const { fqName, shortName } of valueExports) {
    lines.push(`\t${fqName} as ${shortName},`);
  }
  lines.push('};');

  return lines.join('\n');
}

function groupVersionToNamespace(group: string, version: string): string {
  // Convert "external-secrets.io" + "v1" to "ExternalSecretsIoV1"
  // Split on dots, then within each part split on hyphens and capitalize each word
  const groupParts = group
    .split('.')
    .map((part) =>
      part
        .split(/[-_]/)
        .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
        .join(''),
    )
    .join('');
  // Capitalize version, handling hyphens and numbers (e.g. "v1beta1" -> "V1beta1", "v1-beta-1" -> "V1Beta1")
  const versionPascal = version
    .split(/[-_]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
  return `${groupParts}${versionPascal}`;
}

function generateResourceTypes(
  def: ResourceDefinition,
  options: EmitOptions,
  prefix: string,
): string[] {
  const lines: string[] = [];
  const className = prefix + def.kind;
  const specName = `${className}Spec`;
  const specInputName = `${className}SpecInput`;
  const fullSpecName = `${className}FullSpec`;
  const fullSpecInputName = `${className}FullSpecInput`;
  const statusName = `${className}Status`;
  const propsName = `${className}Props`;
  const ro = options.readonly ? 'readonly ' : '';

  // JSDoc
  if (def.description) {
    lines.push(`/** ${def.description} */`);
  }

  // Spec interface — the runtime/observed shape. Properties with a schema default
  // are treated as required because the API server populates them, so composition
  // authors reading `this.xr.spec.*` get non-optional types.
  lines.push(`interface ${specName} {`);
  if (def.specSchema?.properties) {
    lines.push(
      ...generateProperties(def.specSchema.properties, def.specSchema.required, 1, options),
    );
  } else {
    lines.push(`\t[key: string]: unknown;`);
  }
  lines.push(`}`);
  lines.push('');

  // Spec input interface — the shape a user passes to the constructor. Properties
  // with a schema default are optional here because the server fills them in.
  lines.push(`interface ${specInputName} {`);
  if (def.specSchema?.properties) {
    lines.push(
      ...generateProperties(def.specSchema.properties, def.specSchema.required, 1, options, true),
    );
  } else {
    lines.push(`\t[key: string]: unknown;`);
  }
  lines.push(`}`);
  lines.push('');

  // Status interface
  // For Crossplane provider resources, statusSchema is sourced from status.atProvider,
  // so we wrap it back under `atProvider` to keep the path accurate for proxy tracking.
  lines.push(`interface ${statusName} {`);
  if (def.crossplaneProvider && def.statusSchema?.properties) {
    lines.push(`\t${ro}atProvider?: {`);
    lines.push(
      ...generateProperties(def.statusSchema.properties, def.statusSchema.required, 2, options),
    );
    lines.push(`\t};`);
  } else if (def.statusSchema?.properties) {
    lines.push(
      ...generateProperties(def.statusSchema.properties, def.statusSchema.required, 1, options),
    );
  } else {
    lines.push(`\t[key: string]: unknown;`);
  }
  lines.push(`}`);
  lines.push('');

  // Full spec interface (for Crossplane provider resources, includes forProvider, initProvider, etc.)
  // Emitted in two variants: the runtime `FullSpec` (forProvider/initProvider use the
  // defaults-required `Spec`) and the constructor `FullSpecInput` (defaults-optional `SpecInput`).
  if (def.crossplaneProvider && def.fullSpecSchema?.properties) {
    for (const [interfaceName, specRef] of [
      [fullSpecName, specName],
      [fullSpecInputName, specInputName],
    ] as const) {
      lines.push(`interface ${interfaceName} {`);
      for (const [name, schema] of Object.entries(def.fullSpecSchema.properties).sort(([a], [b]) =>
        a.localeCompare(b),
      )) {
        const fullRequired = new Set(def.fullSpecSchema.required ?? []);
        const optional = fullRequired.has(name) ? '' : '?';
        if (name === 'forProvider' || name === 'initProvider') {
          lines.push(`\t${ro}${name}${optional}: ${specRef};`);
        } else {
          const tsType = schemaToType(schema, 1, options);
          if (schema.description) {
            lines.push(`\t/** ${escapeComment(schema.description)} */`);
          }
          lines.push(`\t${ro}${safePropName(name)}${optional}: ${tsType};`);
        }
      }
      lines.push(`}`);
      lines.push('');
    }
  }

  // Props interface (what the user passes to constructor). Uses the input variants
  // so properties with schema defaults can be omitted.
  lines.push(`interface ${propsName} {`);
  if (def.crossplaneProvider && def.fullSpecSchema?.properties) {
    // Use full spec schema so providerConfigRef, deletionPolicy, etc. are included
    lines.push(`\t${ro}spec?: ${fullSpecInputName};`);
  } else {
    lines.push(`\t${ro}spec?: ${specInputName};`);
  }
  // Extra top-level fields (e.g. data/stringData/type for Secret)
  if (def.extraSchema) {
    for (const [name, schema] of Object.entries(def.extraSchema).sort(([a], [b]) =>
      a.localeCompare(b),
    )) {
      if (schema.description) {
        lines.push(`\t/** ${escapeComment(schema.description)} */`);
      }
      const tsType = schemaToType(schema, 1, options);
      lines.push(`\t${ro}${safePropName(name)}?: ${tsType};`);
    }
  }
  lines.push(`\t${ro}metadata?: {`);
  lines.push(`\t\t${ro}name?: string;`);
  lines.push(`\t\t${ro}namespace?: string;`);
  lines.push(`\t\t${ro}labels?: Record<string, string>;`);
  lines.push(`\t\t${ro}annotations?: Record<string, string>;`);
  lines.push(`\t};`);
  lines.push(`}`);
  lines.push('');

  // Typed Resource subclass
  const apiVersionStr = def.group === 'core' ? def.version : `${def.group}/${def.version}`;
  if (def.description) {
    lines.push(`/** ${escapeComment(def.description)} */`);
  }
  lines.push(`class ${className} extends Resource {`);

  if (def.crossplaneProvider && def.fullSpecSchema?.properties) {
    lines.push(`\tdeclare spec: ${fullSpecName};`);
  } else {
    lines.push(`\tdeclare spec: ${specName};`);
  }
  lines.push(`\tdeclare status: ${statusName};`);
  if (def.scope === 'Cluster') {
    lines.push(
      `\tdeclare metadata: { name: string; labels?: Record<string, string>; annotations?: Record<string, string>; [key: string]: unknown };`,
    );
  } else {
    lines.push(
      `\tdeclare metadata: { name: string; namespace?: string; labels?: Record<string, string>; annotations?: Record<string, string>; [key: string]: unknown };`,
    );
  }
  // Typed `resource` config — gives readiness-check callbacks a typed observed document.
  lines.push(
    `\tdeclare resource: ResourceConfig<{ apiVersion: string; kind: string; metadata?: { name?: string; namespace?: string; labels?: Record<string, string>; annotations?: Record<string, string>; [key: string]: unknown }; spec?: ${specName}; status?: ${statusName} }>;`,
  );
  // Extra top-level fields (e.g. data/stringData/type for Secret) must also be
  // declared on the class so TypeScript knows they are valid instance properties.
  if (def.extraSchema) {
    for (const [name, schema] of Object.entries(def.extraSchema).sort(([a], [b]) =>
      a.localeCompare(b),
    )) {
      const tsType = schemaToType(schema, 1, options);
      lines.push(`\tdeclare ${safePropName(name)}?: ${tsType};`);
    }
  }
  lines.push('');
  lines.push(`\tconstructor(scope: Construct, id: string, props?: ${propsName}) {`);
  lines.push(`\t\tsuper(scope, id, {`);
  lines.push(`\t\t\tapiVersion: "${apiVersionStr}",`);
  lines.push(`\t\t\tkind: "${def.kind}",`);
  lines.push(`\t\t\t...props,`);
  lines.push(`\t\t});`);
  lines.push(`\t}`);
  lines.push('');
  lines.push(`\tstatic manifest(props?: ${propsName}): Record<string, unknown> {`);
  lines.push(`\t\treturn {`);
  lines.push(`\t\t\tapiVersion: "${apiVersionStr}",`);
  lines.push(`\t\t\tkind: "${def.kind}",`);
  lines.push(`\t\t\t...props,`);
  lines.push(`\t\t};`);
  lines.push(`\t}`);
  lines.push('');
  lines.push(
    `\tstatic fromExistingByName(scope: Construct, name: string, namespace?: string): ${className} {`,
  );
  lines.push(
    `\t\treturn Resource.fromExistingByName(scope, "${apiVersionStr}", "${def.kind}", name, namespace) as unknown as ${className};`,
  );
  lines.push(`\t}`);
  lines.push(`}`);

  return lines;
}

/**
 *
 * @param props - The properties to generate the interface from
 * @param required - List of required properties
 * @param depth - Level of indentation (for nested objects)
 * @param options - Emit options
 * @param defaultsOptional - When true, properties with a schema default are treated as optional (used for constructor input types). Defaults to false, where defaulted properties are required (the runtime/observed shape).
 * @returns Array of strings representing the generated interface lines
 */
function generateProperties(
  props: Record<string, SchemaProperty>,
  required: string[] | undefined,
  depth: number,
  options: EmitOptions,
  defaultsOptional: boolean = false,
): string[] {
  const lines: string[] = [];
  const indent = '\t'.repeat(depth);
  const requiredSet = new Set(required ?? []);
  const ro = options.readonly ? 'readonly ' : '';

  // Sort properties alphabetically
  const sorted = Object.entries(props).sort(([a], [b]) => a.localeCompare(b));

  for (const [name, schema] of sorted) {
    if (schema.description) {
      lines.push(`${indent}/** ${escapeComment(schema.description)} */`);
    }

    const optional =
      requiredSet.has(name) || (!defaultsOptional && schema.default !== undefined) ? '' : '?';
    const tsType = schemaToType(schema, depth, options);
    lines.push(`${indent}${ro}${safePropName(name)}${optional}: ${tsType};`);
  }

  return lines;
}

function schemaToType(schema: SchemaProperty, depth: number, options: EmitOptions): string {
  if (schema.enum) {
    return schema.enum.map((v) => `"${v}"`).join(' | ');
  }

  switch (schema.type) {
    case 'string':
      return 'string';
    case 'integer':
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'array':
      if (schema.items) {
        const itemType = schemaToType(schema.items, depth, options);
        return `${itemType}[]`;
      }
      return 'unknown[]';
    case 'object': {
      if (schema.additionalProperties) {
        if (typeof schema.additionalProperties === 'boolean') {
          return 'Record<string, unknown>';
        }
        const valType = schemaToType(schema.additionalProperties, depth, options);
        return `Record<string, ${valType}>`;
      }
      if (schema.properties) {
        return generateInlineObject(schema.properties, schema.required, depth, options);
      }
      if (schema['x-kubernetes-preserve-unknown-fields']) {
        return 'Record<string, unknown>';
      }
      return 'Record<string, unknown>';
    }
    default:
      return 'unknown';
  }
}

function generateInlineObject(
  props: Record<string, SchemaProperty>,
  required: string[] | undefined,
  depth: number,
  options: EmitOptions,
): string {
  const lines: string[] = [];
  const indent = '\t'.repeat(depth + 1);
  const requiredSet = new Set(required ?? []);
  const sorted = Object.entries(props).sort(([a], [b]) => a.localeCompare(b));
  const ro = options.readonly ? 'readonly ' : '';

  lines.push('{');
  for (const [name, schema] of sorted) {
    if (schema.description) {
      lines.push(`${indent}/** ${escapeComment(schema.description)} */`);
    }
    const optional = requiredSet.has(name) || schema.default !== undefined ? '' : '?';
    const tsType = schemaToType(schema, depth + 1, options);
    lines.push(`${indent}${ro}${safePropName(name)}${optional}: ${tsType};`);
  }
  lines.push(`${'\t'.repeat(depth)}}`);

  return lines.join('\n');
}

function safePropName(name: string): string {
  if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name)) return name;
  return `"${name}"`;
}

function escapeComment(text: string): string {
  return text.replace(/\*\//g, '* /').replace(/\n/g, ' ');
}
