import type { ResourceDefinition, SchemaProperty } from '../schema/index.js';

/** Options controlling code generation output. */
export interface EmitOptions {
  /** Prefix all interface properties with `readonly`. Default: false. */
  readonly?: boolean;
  /** Wrap all exports in a namespace per group+version. Default: false. */
  useNamespace?: boolean;
  /** Prefix class names with namespace to avoid collisions. Default: false. */
  fullyQualifiedClassNames?: boolean;
}

/**
 * Generate TypeScript source code for a group of resource definitions.
 * Produces one file per API group containing interfaces and typed Resource subclasses.
 */
export function generateGroupFile(
  group: string,
  defs: ResourceDefinition[],
  options: EmitOptions = {},
): string {
  const lines: string[] = [];

  lines.push(`// Generated by @xplane/codegen — do not edit`);
  lines.push(`import { type Construct } from "constructs";`);
  lines.push(`import { Resource, type ResourceOptions } from "@xplane/core";`);
  lines.push('');

  if (options.useNamespace && defs.length > 0) {
    // Use namespace to avoid collisions (e.g. 'Record' class shadowing Record type)
    const namespaceName = groupVersionToNamespace(group, defs[0]!.version);
    lines.push(`export namespace ${namespaceName} {`);
    lines.push(`type Record = globalThis.Record;`);
    lines.push('');
    for (const def of defs) {
      lines.push(...generateResourceTypes(def, options, true, group, def.version));
      lines.push('');
    }
    lines.push('}');
  } else {
    for (const def of defs) {
      lines.push(...generateResourceTypes(def, options, false, group, def.version));
      lines.push('');
    }
  }

  return lines.join('\n');
}

function groupVersionToNamespace(group: string, version: string): string {
  // Convert "external-secrets.io" + "v1" to "ExternalSecretsIoV1"
  // Split on dots, then within each part split on hyphens and capitalize each word
  const groupParts = group
    .split('.')
    .map((part) =>
      part
        .split(/[-_]/)
        .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
        .join(''),
    )
    .join('');
  // Capitalize version, handling hyphens and numbers (e.g. "v1beta1" -> "V1beta1", "v1-beta-1" -> "V1Beta1")
  const versionPascal = version
    .split(/[-_]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
  return `${groupParts}${versionPascal}`;
}

function generateResourceTypes(
  def: ResourceDefinition,
  options: EmitOptions,
  inNamespace: boolean = false,
  group?: string,
  version?: string,
): string[] {
  const lines: string[] = [];
  let className = def.kind;
  if (options.fullyQualifiedClassNames && group && version) {
    const prefix = groupVersionToNamespace(group, version);
    className = prefix + def.kind;
  }
  const specName = `${className}Spec`;
  const statusName = `${className}Status`;
  const propsName = `${className}Props`;
  const ro = options.readonly ? 'readonly ' : '';
  const indent = inNamespace ? '\t' : '';

  // JSDoc
  if (def.description) {
    lines.push(`${indent}/** ${def.description} */`);
  }

  // Spec interface
  lines.push(`${indent}export interface ${specName} {`);
  if (def.specSchema?.properties) {
    lines.push(
      ...generateProperties(def.specSchema.properties, def.specSchema.required, 1, options),
    );
  } else {
    lines.push(`\t[key: string]: unknown;`);
  }
  lines.push(`${indent}}`);
  lines.push('');

  // Status interface
  // For Crossplane provider resources, statusSchema is sourced from status.atProvider,
  // so we wrap it back under `atProvider` to keep the path accurate for proxy tracking.
  lines.push(`${indent}export interface ${statusName} {`);
  if (def.crossplaneProvider && def.statusSchema?.properties) {
    const ro = options.readonly ? 'readonly ' : '';
    lines.push(`\t${ro}atProvider?: {`);
    lines.push(
      ...generateProperties(def.statusSchema.properties, def.statusSchema.required, 2, options),
    );
    lines.push(`\t};`);
  } else if (def.statusSchema?.properties) {
    lines.push(
      ...generateProperties(def.statusSchema.properties, def.statusSchema.required, 1, options),
    );
  } else {
    lines.push(`\t[key: string]: unknown;`);
  }
  lines.push(`${indent}}`);
  lines.push('');

  // Props interface (what the user passes to constructor)
  lines.push(`${indent}export interface ${propsName} {`);
  if (def.crossplaneProvider && def.fullSpecSchema?.properties) {
    // Use full spec schema so providerConfigRef, deletionPolicy, etc. are included
    lines.push(`\t${ro}spec?: {`);
    for (const [name, schema] of Object.entries(def.fullSpecSchema.properties).sort(([a], [b]) =>
      a.localeCompare(b),
    )) {
      const fullRequired = new Set(def.fullSpecSchema.required ?? []);
      const optional = fullRequired.has(name) ? '' : '?';
      if (name === 'forProvider' || name === 'initProvider') {
        lines.push(`\t\t${ro}${name}${optional}: ${specName};`);
      } else {
        const tsType = schemaToType(schema, 2, options);
        if (schema.description) {
          lines.push(`\t\t/** ${escapeComment(schema.description)} */`);
        }
        lines.push(`\t\t${ro}${safePropName(name)}${optional}: ${tsType};`);
      }
    }
    lines.push(`\t};`);
  } else {
    lines.push(`\t${ro}spec?: ${specName};`);
  }
  // Extra top-level fields (e.g. data/stringData/type for Secret)
  if (def.extraSchema) {
    for (const [name, schema] of Object.entries(def.extraSchema).sort(([a], [b]) =>
      a.localeCompare(b),
    )) {
      if (schema.description) {
        lines.push(`\t/** ${escapeComment(schema.description)} */`);
      }
      const tsType = schemaToType(schema, 1, options);
      lines.push(`\t${ro}${safePropName(name)}?: ${tsType};`);
    }
  }
  lines.push(`\t${ro}metadata?: {`);
  lines.push(`\t\t${ro}name?: string;`);
  lines.push(`\t\t${ro}namespace?: string;`);
  lines.push(`\t\t${ro}labels?: Record<string, string>;`);
  lines.push(`\t\t${ro}annotations?: Record<string, string>;`);
  lines.push(`\t};`);
  lines.push(`}`);
  lines.push('');

  // Typed Resource subclass
  const apiVersionStr = def.group === 'core' ? def.version : `${def.group}/${def.version}`;
  if (def.description) {
    lines.push(`${indent}/** ${escapeComment(def.description)} */`);
  }
  lines.push(`${indent}export class ${className} extends Resource<${specName}, ${statusName}> {`);
  lines.push(
    `${indent}\tconstructor(scope: Construct, id: string, props?: ${propsName}, options?: ResourceOptions) {`,
  );
  lines.push(`${indent}\t\tsuper(scope, id, {`);
  lines.push(`${indent}\t\t\tapiVersion: "${apiVersionStr}",`);
  lines.push(`${indent}\t\t\tkind: "${def.kind}",`);
  lines.push(`${indent}\t\t\t...props,`);
  lines.push(`${indent}\t\t\tspec: props?.spec as unknown as Record<string, unknown>,`);
  lines.push(`${indent}\t\t}, options);`);
  lines.push(`${indent}\t}`);
  lines.push(`${indent}}`);

  return lines;
}

function generateProperties(
  props: Record<string, SchemaProperty>,
  required: string[] | undefined,
  depth: number,
  options: EmitOptions,
): string[] {
  const lines: string[] = [];
  const indent = '\t'.repeat(depth);
  const requiredSet = new Set(required ?? []);
  const ro = options.readonly ? 'readonly ' : '';

  // Sort properties alphabetically
  const sorted = Object.entries(props).sort(([a], [b]) => a.localeCompare(b));

  for (const [name, schema] of sorted) {
    if (schema.description) {
      lines.push(`${indent}/** ${escapeComment(schema.description)} */`);
    }

    const optional = requiredSet.has(name) ? '' : '?';
    const tsType = schemaToType(schema, depth, options);
    lines.push(`${indent}${ro}${safePropName(name)}${optional}: ${tsType};`);
  }

  return lines;
}

function schemaToType(schema: SchemaProperty, depth: number, options: EmitOptions): string {
  if (schema.enum) {
    return schema.enum.map((v) => `"${v}"`).join(' | ');
  }

  switch (schema.type) {
    case 'string':
      return 'string';
    case 'integer':
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'array':
      if (schema.items) {
        const itemType = schemaToType(schema.items, depth, options);
        return `${itemType}[]`;
      }
      return 'unknown[]';
    case 'object': {
      if (schema.additionalProperties) {
        if (typeof schema.additionalProperties === 'boolean') {
          return 'Record<string, unknown>';
        }
        const valType = schemaToType(schema.additionalProperties, depth, options);
        return `Record<string, ${valType}>`;
      }
      if (schema.properties) {
        return generateInlineObject(schema.properties, schema.required, depth, options);
      }
      if (schema['x-kubernetes-preserve-unknown-fields']) {
        return 'Record<string, unknown>';
      }
      return 'Record<string, unknown>';
    }
    default:
      return 'unknown';
  }
}

function generateInlineObject(
  props: Record<string, SchemaProperty>,
  required: string[] | undefined,
  depth: number,
  options: EmitOptions,
): string {
  const lines: string[] = [];
  const indent = '\t'.repeat(depth + 1);
  const requiredSet = new Set(required ?? []);
  const sorted = Object.entries(props).sort(([a], [b]) => a.localeCompare(b));
  const ro = options.readonly ? 'readonly ' : '';

  lines.push('{');
  for (const [name, schema] of sorted) {
    if (schema.description) {
      lines.push(`${indent}/** ${escapeComment(schema.description)} */`);
    }
    const optional = requiredSet.has(name) ? '' : '?';
    const tsType = schemaToType(schema, depth + 1, options);
    lines.push(`${indent}${ro}${safePropName(name)}${optional}: ${tsType};`);
  }
  lines.push(`${'\t'.repeat(depth)}}`);

  return lines.join('\n');
}

function safePropName(name: string): string {
  if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name)) return name;
  return `"${name}"`;
}

function escapeComment(text: string): string {
  return text.replace(/\*\//g, '* /').replace(/\n/g, ' ');
}
