import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { ResourceDefinition } from '../schema/index.js';
import type { EmitOptions } from './emit.js';
import { generateGroupFile } from './emit.js';

/** Options for writeOutput. */
export interface WriteOptions extends EmitOptions {
  /** Skip emitting the barrel index.ts. Default: false. */
  noBarrel?: boolean;
}

/**
 * Group resource definitions by API group and write TypeScript files.
 * Creates one .ts file per group+version with a barrel index.ts that uses
 * namespaced re-exports to avoid name collisions between groups and versions.
 */
export function writeOutput(
  defs: ResourceDefinition[],
  outputDir: string,
  options: WriteOptions = {},
): void {
  mkdirSync(outputDir, { recursive: true });

  // Group by API group + version (e.g. "ec2.aws.upbound.io/v1beta1")
  const groups = new Map<string, ResourceDefinition[]>();
  for (const def of defs) {
    const key = `${def.group}/${def.version}`;
    const existing = groups.get(key) ?? [];
    existing.push(def);
    groups.set(key, existing);
  }

  const barrelExports: string[] = [];
  barrelExports.push(`// Generated by @xplane/codegen — do not edit`);
  barrelExports.push('');

  for (const [key, groupDefs] of groups) {
    const [group, version] = key.split('/') as [string, string];
    const fileName = groupVersionToFileName(group, version);
    const content = generateGroupFile(group, groupDefs, options);

    writeFileSync(join(outputDir, `${fileName}.ts`), content);
    barrelExports.push(
      `export * as ${groupVersionToNamespace(group, version)} from "./${fileName}.js";`,
    );
  }

  if (!options.noBarrel) {
    barrelExports.push('');
    writeFileSync(join(outputDir, 'index.ts'), barrelExports.join('\n'));
  }
}

/**
 * Convert an API group + version to a safe file name.
 * e.g. "ec2.aws.upbound.io", "v1beta1" → "ec2.aws.upbound.io.v1beta1"
 */
function groupVersionToFileName(group: string, version: string): string {
  return `${group.replace(/\//g, '-')}.${version}`;
}

/**
 * Convert an API group + version to a valid JS namespace identifier.
 * e.g. "ec2.aws.upbound.io", "v1beta1" → "ec2_aws_upbound_io_v1beta1"
 */
function groupVersionToNamespace(group: string, version: string): string {
  return `${group.replace(/[^a-zA-Z0-9]/g, '_')}_${version.replace(/[^a-zA-Z0-9]/g, '_')}`;
}
