name: Release Please

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.CICD_APP_ID }}
          private-key: ${{ secrets.CICD_APP_PRIVKEY }}
          repositories: ${{ github.event.repository.name }}
      - name: Run release-please
        uses: googleapis/release-please-action@v5
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
